// Pixel-art UI elements — hearts, logo, moon, icons.
import { NNTV } from './palette.js';

export const HEART_ART = [
    '................',
    '..kkkk....kkkk..',
    '.krrrhk..krrrhk.',
    'krrwrrrkkrrrrhk.',
    'krwrrrrrrrrrrhk.',
    'krrrrrrrrrrrrhk.',
    'krrrrrrrrrrrhhk.',
    'krrrrrrrrrrrhhk.',
    '.krrrrrrrrrrhk..',
    '.khrrrrrrrrhhk..',
    '..khrrrrrrhhk...',
    '...khrrrrhhk....',
    '....khrrhhk.....',
    '.....khhhk......',
    '......khk.......',
    '.......k........',
];
export const HEART_ART_EMPTY = HEART_ART.map(r => r.replace(/[rwh]/g, 'e'));
export const HEART_PAL = {
    k: NNTV.ink, r: NNTV.scarfRed, h: '#8a1a22',
    w: NNTV.cream, e: NNTV.dusk,
};

export const MOON_ART = [
    '........kkkkk.......',
    '......kkggghhk......',
    '.....kgggghhhhk.....',
    '....kggghhhhhhhk....',
    '...kggghhhhhhhhhk...',
    '...kgghhhhhhhhhhk...',
    '..kggghhhhhhhhhhhk..',
    '..kgghhhhhhhhhhhhk..',
    '..kgghhhhhhhhhhhhk..',
    '..kgghhhhhhhhhhhhk..',
    '..kgghhhhhhhhhhhhk..',
    '..kgghhhhhhhhhhhhk..',
    '..kggghhhhhhhhhhhk..',
    '...kgghhhhhhhhhhk...',
    '...kggghhhhhhhhhk...',
    '....kggghhhhhhhk....',
    '.....kgggghhhhk.....',
    '......kkggghhk......',
    '........kkkkk.......',
    '....................',
];
export const MOON_PAL = { k: NNTV.ink, g: NNTV.cream, h: NNTV.moonGlow };

// 16-wide icons — 'k' outline, 'w' fill.
const padIcon = (s) => s.split('\n').filter(Boolean).map(r => r.padEnd(16, '.').slice(0, 16));
export const ICON_PAL = { k: NNTV.ink, w: NNTV.moonlight, a: NNTV.scarfRed };

export const ICON_UNDO = padIcon(`
................
................
.....wwww.......
....w....w......
...w......w.....
..w...wwww.w....
..w..w.....w....
..w..w..........
.wwww.w.........
.wwwww..........
..www...........
...w............
................
................
................
................`);

export const ICON_REDO = padIcon(`
................
................
.......wwww.....
......w....w....
.....w......w...
....w.wwww...w..
....w.....w..w..
..........w..w..
.........w.wwww.
..........wwwww.
...........www..
............w...
................
................
................
................`);

export const ICON_EYE = padIcon(`
................
................
...wwwwwwwww....
..w.........w...
.w...wwwww...w..
w...w.....w...w.
w...w.www.w...w.
w...w.www.w...w.
w...w.....w...w.
.w...wwwww...w..
..w.........w...
...wwwwwwwww....
................
................
................
................`);

export const ICON_PAUSE = padIcon(`
................
...ww.....ww....
...ww.....ww....
...ww.....ww....
...ww.....ww....
...ww.....ww....
...ww.....ww....
...ww.....ww....
...ww.....ww....
...ww.....ww....
...ww.....ww....
...ww.....ww....
................
................
................
................`);

export const ICON_SETTINGS = padIcon(`
................
.....wwww.......
....w....w......
...w..ww..w.....
..w..wwww..w....
..w..wwww..w....
.w....ww....w...
.w..........w...
.w..........w...
.w....ww....w...
..w..wwww..w....
..w..wwww..w....
...w..ww..w.....
....w....w......
.....wwww.......
................`);

export const ICON_LANG = padIcon(`
................
.....wwww.......
....wwwwww......
...ww....ww.....
..ww..ww..ww....
.ww..w..w..ww...
.w..ww..ww..w...
.w..ww..ww..w...
.w..ww..ww..w...
.ww..w..w..ww...
..ww..ww..ww....
...ww....ww.....
....wwwwww......
.....wwww.......
................
................`);

export const ICON_ARROW = padIcon(`
................
................
.......w........
......ww........
.....www........
....wwww........
...wwwww........
..wwwwwwwwww....
...wwwww........
....wwww........
.....www........
......ww........
.......w........
................
................
................`);

// Simple "NNTV" wordmark — compact 36×9 to fit menu header.
export const LOGO_ART = [
    '....................................',
    '.k..k.k...k.kkkk.k...k..kkk.k...k...',
    '.kk.k.kk..k.k.k..kk..k.k....kk..k...',
    '.k.kk.k.k.k.k.k..k.k.k.k....k.k.k...',
    '.k..k.k..kk.k.k..k..kk.k....k..kk...',
    '.k..k.k...k.kkkk.k...k..kkk.k...k...',
    '....................................',
    '....................................',
    '....................................',
];
export const LOGO_PAL = { k: NNTV.moonlight };
